//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeCensus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonRole
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public int Role { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public System.DateTime InputDate { get; set; }
        public int InputBy { get; set; }
        public System.DateTime AmendDate { get; set; }
        public int AmendBy { get; set; }
    }
}
