//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeCensus
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncDetail
    {
        public int ID { get; set; }
        public int SyncHistoryID { get; set; }
        public System.Guid RowID { get; set; }
        public byte Action { get; set; }
    
        public virtual SyncHistory SyncHistory { get; set; }
    }
}
