//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeCensus
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SyncHistory()
        {
            this.SyncDetails = new HashSet<SyncDetail>();
        }
    
        public int ID { get; set; }
        public string TableName { get; set; }
        public System.DateTime SyncDateTime { get; set; }
        public int SyncBy { get; set; }
        public string Note { get; set; }
        public byte Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SyncDetail> SyncDetails { get; set; }
    }
}
