//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeCensus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tradecensusEntities : DbContext
    {
        public tradecensusEntities()
            : base("name=tradecensusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Area> Areas { get; set; }
        public DbSet<Config> Configs { get; set; }
        public DbSet<Outlet> Outlets { get; set; }
        public DbSet<OutletImage> OutletImages { get; set; }
        public DbSet<OutletType> OutletTypes { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<PersonRole> PersonRoles { get; set; }
        public DbSet<Province> Provinces { get; set; }
        public DbSet<SyncDetail> SyncDetails { get; set; }
        public DbSet<SyncHistory> SyncHistories { get; set; }
        public DbSet<Zone> Zones { get; set; }
    }
}
