//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeCensus
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectionSession
    {
        public int ID { get; set; }
        public string Uuid { get; set; }
        public string Model { get; set; }
        public string Platform { get; set; }
        public string Version { get; set; }
        public string Manufacturer { get; set; }
        public string Token { get; set; }
        public string AppVersion { get; set; }
        public System.DateTime AmendDate { get; set; }
        public int AmendBy { get; set; }
    }
}
